[package]
name = "native_model"
version = "0.4.11"
authors = ["Vincent Herlemont <vincent@herlemont.fr>"]
edition = "2021"
description = "A thin wrapper around serialized data which add information of identity and version."
license = "MIT"
repository = "https://github.com/vincent-herlemont/native_model"
readme = "README.md"
build = "build.rs"
keywords = ["serialization", "interoperability", "data-consistency", "flexibility", "performance"]
categories = ["data-structures", "encoding", "rust-patterns"]

[workspace]
members = ["native_model_macro"]

[dependencies]
<<<<<<< HEAD
zerocopy = { version = "0.7.32", features = [ "derive"] }
thiserror = "1.0"
anyhow = "1.0"
native_model_macro = { version = "0.4.11", path = "native_model_macro" }
=======
zerocopy = { version = "0.7.33", features = ["derive"] }
thiserror = "1.0.59"
anyhow = "1.0.82"
native_model_macro = { version = "0.4.19", path = "native_model_macro" }
>>>>>>> b6d3bd4 (Removed `#![feature(doc_cfg)]` nightly feature)

serde = { version = "1.0", features = ["derive"], optional = true }
bincode_1_3 = { package = "bincode", version = "1.3", optional = true }
bincode_2_rc = { package = "bincode", version = "2.0.0-rc.3", features = ["serde"], optional = true }
<<<<<<< HEAD
postcard_1_0 = { package = "postcard", version = "1.0", features = ["alloc"], optional = true }
=======
postcard_1_0 = { package = "postcard", version = "1.0.8", features = ["alloc"], optional = true }
rmp_serde_1_3 = { package = "rmp-serde", version = "1.3", optional = true }
>>>>>>> 3576bad (Improved codec docs & support for `rmp-serde` `1.3`)

[dev-dependencies]
serde_json = "1.0"
criterion = { version = "0.5.1" }
skeptic = "0.13"

[features]
default = ["serde", "bincode_1_3"]

[[bench]]
name = "overhead"
harness = false

[build-dependencies]
skeptic = "0.13"